inhibit_all_warnings!
install! 'cocoapods', :deterministic_uuids => false
use_frameworks!

target 'KSYAirStreamer_Example' do
  pod 'Bugly'
  pod 'GPUImage'
  pod 'libksygpulive/libksygpulive', '~> 2.9.2'
  pod 'KSYAirStreamer',  :path => '../'

  target 'KSYAirStreamer_Tests' do
    inherit! :search_paths
  end
end
